### ISSUE TITLE
Add blur to pregame countdown sceens

### ISSUE THREAD

**Issue by josef-karpinski** [circlegame/circlegame-neo#21]

**Comment by manos-alex** [comment]
We can use CSS to add a blur filter to the sketch div returned in `P5Wrapper.jsx`.
```jsx
...
  return (
    <div style={{ overflow: 'hidden' }}>
      <div style={{filter: 'blur(12px)'}} ref={sketchRef} />
    </div>
  );
```
We can communicate the `gameState()` from inside the sketch to only apply the blur during "pregame" and/or "countdown".
